require:
  - rubocop-rails

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'

Style/Documentation:
  Exclude:
    - 'db/migrate/*.rb'
    - 'test/*_helper.rb'
    - 'config/application.rb'
    - 'app/*/application_*.rb'